### ISSUE TITLE
[Flicking] Makes panels can have paddings.

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs#226]
## Description

If panels have paddings, panels overrides flicking area.

## Steps to check or reproduce

http://codepen.io/jongmoon/pen/ZWdGgQ

```css
#wrapper {
  width:100%;
  height:300px;
}

div.content {
  padding:0 100px;
}
```

```js
$("#wrapper").flicking();
```

### Result

![image](https://cloud.githubusercontent.com/assets/3255471/15390535/35963778-1df7-11e6-80bb-5b2a88e2c19d.png)

The red panel overrides flicking area.
